### PR TITLE
bugfix/server: Add module lifecycle context to Server

### LINKED ISSUE #570: [Bug] CONNECTION_FAILED: bot is not ready
### Version

0.260326.1200-hotfix

### System Information

macOS

### Category

Remote Control

### Scenario

I am using feishu bot, but sometimes, the remote bot will exit will error `CONNECTION_FAILED: bot is not ready`, and I have to disable/re-enable it.

### Steps to Reproduce

_No response_

### Logs / Error Output

```shell
2026-03-26 15:42:34 [INFO] [imbot] Message sent successfully: ID=om_x100b537a786e38b0c49ab73ace4ab4c
[assistant] [1.1] tingly-box:
  Hi! I'm @tb (Tingly-Box Smart Guide), your navigation and coordination assistant.

  I can help you:
  - Navigate and understand your projects
  - Set up and prepare your workspace
  - Answer questions and provide information
  - Coordinate with specialized assistants like @cc for code implementation

  What would you like to work on today?

  Thinking: "The user has just said \"hi\". I should greet them and ask what they need help with. I'm the Tingly-Box Smart Guide (@tb), the entry point for users working with Tingly Dev.\n\nI should keep my response concise and friendly, and ask what they'd like to work on."
2026-03-26 15:42:35 [INFO] [imbot] Card sent successfully: ID=om_x100b537a78667ca8c44bfe46d581790
INFO[4741] SmartGuide execution completed via callback   chatID=ou_deedb4d7dde1d968609135f9b2c094a1 duration=6093 sessionID=ou_deedb4d7dde1d968609135f9b2c094a1 success=true
INFO[4741] SmartGuide execution completed                duration_ms=6093 session_id=ou_deedb4d7dde1d968609135f9b2c094a1 success=true
INFO[4741] SmartGuide execution completed                chatID=ou_deedb4d7dde1d968609135f9b2c094a1 success=true
2026-03-26 15:54:58 [INFO] [imbot] feishu received P2 message: &{EventV2Base:0x14000010348 EventReq:0x14000a086c0 Event:0x14000a6a350}
INFO[5485] Chat ID: ou_deedb4d7dde1d968609135f9b2c094a1
INFO[5485] Executing agent handoff                       chat_id=ou_deedb4d7dde1d968609135f9b2c094a1 from_agent=tingly-box project= session_id= to_agent=claude
INFO[5485] Agent handoff completed                       chatID=ou_deedb4d7dde1d968609135f9b2c094a1 fromAgent=tingly-box project= toAgent=claude
WARN[5485] Failed to send message                        error="CONNECTION_FAILED: bot is not ready"
2026-03-26 15:55:30 [INFO] [imbot] feishu received P2 message: &{EventV2Base:0x140005344b0 EventReq:0x14000a4c150 Event:0x140009b2090}
INFO[5516] Chat ID: ou_deedb4d7dde1d968609135f9b2c094a1
WARN[5516] Failed to send message                        error="CONNECTION_FAILED: bot is not ready"
2026-03-26 15:55:31 [INFO] [imbot] feishu received P2 message: &{EventV2Base:0x140005f5020 EventReq:0x1400068ef00 Event:0x14000b458c0}
INFO[5518] Chat ID: ou_deedb4d7dde1d968609135f9b2c094a1
WARN[5518] Failed to send message                        error="CONNECTION_FAILED: bot is not ready"
```

### PR DESCRIPTION
**Pull request by seviezhou**
Introduce moduleCtx/moduleCancel fields to Server to manage long-lived background components created during setup. NewServer now initializes and stores the module context (instead of creating a transient ctx that was immediately canceled), passes it to setupRoutes, and Stop will cancel the module context when shutting down. Add server_lifecycle_test.go to verify the module context remains active after NewServer and is canceled by moduleCancel.

Try to fix #570 .

### CODE REVIEW

File: internal/server/server.go [hunk 1]
```diff
@@ -290,15 +294,16 @@ func (s *Server) GetOrCreateScenarioSink(scenario typ.RuleScenario) *obs.Sink {
...
+	moduleCtx, moduleCancel := context.WithCancel(context.Background())
 
 	// Start with default options
 	allOpts := append([]ServerOption{WithDefault()}, opts...)
 
 	// Default options
 	server := &Server{
-		config: cfg,
+		config:       cfg,
+		moduleCtx:    moduleCtx,
```
Comment (FFengIll) [inline internal/server/server.go]: juset named as ctx, and cancel is ok
